// <auto-generated />
using System;
using Fantastical.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fantastical.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190805200858_imageupload3")]
    partial class imageupload3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fantastical.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<bool>("isAdmin");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "00000000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2bea6894-b458-417e-964a-38e912ac6620",
                            Email = "Admin@Admin.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBwKyVBdGWRfaPhOPa4G0BA3zewLqmZv5YvwoEo7h8GqJ77YVVAi7A1z+KYDupjGUg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "Admin@Admin.com",
                            isAdmin = true
                        },
                        new
                        {
                            Id = "12345678-wega-werw-jyjt-kepsfienqp",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2c80585d-eddd-4299-a61e-33c147e1b01d",
                            Email = "ThisGuy@ThisGuy.com",
                            EmailConfirmed = true,
                            FirstName = "This",
                            LastName = "Guy",
                            LockoutEnabled = false,
                            NormalizedEmail = "THISGUY@THISGUY.COM",
                            NormalizedUserName = "THISGUY@THISGUY.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPYmWvw+33c6rte82mfAFyXGbZ63KFm0nlCiKeFD7exwAuW6HIOWC4OUKQSwBeaCAg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5r423999-f4g5-93i4-2rtt-255re563256",
                            TwoFactorEnabled = false,
                            UserName = "ThisGuy@ThisGuy.com",
                            isAdmin = false
                        });
                });

            modelBuilder.Entity("Fantastical.Models.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImagePath");

                    b.Property<string>("Lore")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Region")
                        .IsRequired();

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Creature");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "Anansi.jpg",
                            Lore = "In West African lore, Anansi is a trickster character who often takes the shape of a spider and is considered the spirit of all knowledge of stories. Tales of Anansi were part of an exclusively oral tradition, which was fitting as he himself was seen as synonymous with skill and wisdom in speech.",
                            Name = "Anansi",
                            Region = "West Africa, Jamaica, United States",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "HuginnandMuninn.jpg",
                            Lore = "Huginn and Muninn (Old Norse for 'thought' and 'memory' or 'mind', respectively) are a pair of ravens that fly all over Midgard (the world) in order to gather information and bring it to the god Odin. Scholars have linked the god's relation to Huginn and Muninn to the shamanic practice of going on a trance-like journey.",
                            Name = "Huginn and Muninn",
                            Region = "Scandinavia",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "Mothman.jpg",
                            Lore = "Mothman is a Cryptid out of West Virginia in the United States. He was first spotted in November 1966 by five men digging a grave in a cemetery near Clendenin, and was described as a man-like figure flying low over their heads. Several days later, he was seen again, this time by two couples who reported a large, gray, flying man with ten-foot wings whose eyes glowed red and who followed their car for some time. A little over a year later in December 1967, the Silver Bridge, which spanned the Ohio river between Point Pleasant, West Virginia, and Gallipolis, Ohio, collapsed and Mothman was connected to the tragedy. Today, Mothman is one of the more well known Cryptids, thanks to books, movies, a statue and a museum dedicated to him in Point Pleasant.There is even a festival held in September every year by the museum and people flock to see speakers, cosplay, and fun activities for kids.",
                            Name = "Mothman",
                            Region = "West Virginia",
                            UserId = "12345678-wega-werw-jyjt-kepsfienqp"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "Unicorn.jpg",
                            Lore = "The Unicorn is a legendary creature, often described as a white horse-like animal with a long spiral horn and cloven hooves. The first known depictions are found in the areas of the Indus Valley Civilization, and are mentioned with some frequency in the annals of Greek history. Interestingly, they are mentioned in accounts of natural history rather than mythology because they were believed by the Greeks to have truly existed in faraway lands. In the Middle Ages and Renaissance, it was said that the unicorn could only be tamed by a virgin, and was emblematic of chaste love and faithful marriage.The horns were said to be made of a substance called alicorn, and it was believed they held magical, medicinal properties.",
                            Name = "Unicorn",
                            Region = "Europe",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "Wyvern.jpg",
                            Lore = "A Wyvern is a legendary, bipedal dragon with a tail often ending in a diamond or arrow shaped tip. The creature frequently appears in heraldry and literature, video games, and modern fantasy. There is very little differentiation between Wyverns and Dragons, the key difference being the number of legs.",
                            Name = "Wyvern",
                            Region = "Europe",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "Sphinx.jpg",
                            Lore = "A Sphinx is a mystical creature with the head of a human and the body of a lion and, sometimes, the wings of a bird. In Greek mythology, those who could not answer the Sphinx's riddles were eaten. In Egyptian, the Sphinx was regarded more as a benevolent creature, but both were often viewed as guardians of temples.",
                            Name = "Sphinx",
                            Region = "Persia, Greece, and Egypt",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "Kraken.jpg",
                            Lore = "A Kraken is a giant cephalopod-like sea-monster in Scandinavian folklore, said to haunt the coasts of Greenland and Norway in order to terrorize unwary sailors.",
                            Name = "Kraken",
                            Region = "Scandinavia",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "BlackDog.jpg",
                            Lore = "A Black Dog is a spectral entity found primarily in the folklore of the British Isles. It is a nocturnal apparition often described as a ghost or hellhound, and was said to be an enormous dog with glowing eyes. Its appearance was frequently regarded as a portent of death, and is associated with crossroads, places of execution, and ancient pathways. It is difficult to discern where exactly the tales of the Black Dog began, but throughout European mythology, dogs have been associated with death.",
                            Name = "Black Dog",
                            Region = "British Isles",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "Thunderbird.jpg",
                            Lore = "The Thunderbird is a legendary creature in certain North American Indigenous Peoples' culture and history. It is a being of power and strength, and is most frequently depicted in the art, songs, and oral history of the Pacific Northwest Coast cultures, but also can be found in others. In mythology, the Thunderbird controls the upper world while the underworld is controlled by the Underwater Panther or Great Horned Serpent. In other mythologies, the Thunderbirds reside on a great floating mountain and control the rain and hail and are regarded as warriors, and are the enemies of the Great Horned Snakes.",
                            Name = "Thunderbird",
                            Region = "Pacific Northwest Coast",
                            UserId = "12345678-wega-werw-jyjt-kepsfienqp"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Fantastical.Models.Creature", b =>
                {
                    b.HasOne("Fantastical.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Fantastical.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Fantastical.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fantastical.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Fantastical.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
